version: '3'
services:
        webApp:
                image: jboss/wildfly
                volumes:
                   - ~/deployments:/opt/jboss/wildfly/standalone/deployments
                ports:
                   - 8080:8080   
